language: cpp

compiler:
  - gcc

before_install:
  # support C++11 with g++ 4.8 and latest Boost
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8 scons libcppunit-dev boost1.55
  - export CXX=g++-4.8

script:
  - scons
  - cd tests/cppunit
  - export LD_LIBRARY_PATH=../../src
  - ./testall
  - cd ../..
