# author: Philippe Proulx <eepp.ca>


import os.path


Import('root_env')

cppunit = SConscript(os.path.join('cppunit', 'SConscript'),
                     exports=['root_env'])
SConscript(os.path.join('tools', 'SConscript'), exports=['root_env'])
Return('cppunit')
