# author: Philippe Proulx <eepp.ca>


import os.path


Import('root_env')

target = 'testall'

interval_tests = [
    'IntIntervalTest.cpp',
    'StringIntervalTest.cpp',
]

node_tests = [
    'NodeTest.cpp',
]

subs = [
    ('interval', interval_tests),
    ('node', node_tests),
]

sources = ['main.cpp']
for base, files in subs:
    sources += [os.path.join('tests', base, f) for f in files]

testall = root_env.Program(target=target, source=sources,
                           LIBS=['cppunit', 'delorean'],
                           LIBPATH='#/src')
Return('testall')
