# author: Philippe Proulx <eepp.ca>


import os.path


Import('root_env')

target = 'delorean'

main_sources = [
    'AbstractHistory.cpp',
    'AbstractHistoryFile.cpp',
    'HistoryFileSink.cpp',
]
ex_sources = [
    'UnknownIntervalType.cpp',
    'UnknownNodeType.cpp',
]
interval_sources = [
    'IntervalSerializer.cpp',
    'IntervalDeserializer.cpp',
    'AbstractInterval.cpp',
    'StringInterval.cpp',
]
node_sources = [
    'NodeSerializer.cpp',
    'NodeDeserializer.cpp',
    'AbstractNode.cpp',
    'BranchNode.cpp',
    'LeafNode.cpp',
]

subs = [
    ('.', main_sources),
    ('ex', ex_sources),
    ('interval', interval_sources),
    ('node', node_sources),
]

sources = []
for base, files in subs:
    sources += [os.path.join(base, f) for f in files]

root_env.SharedLibrary(target=target, source=sources,
                       LIBS='boost_system')
