# common parameters
#
# author:	Philippe Proulx <philippe.proulx@polymtl.ca>
CPP = g++
CPPFLAGS = -g -Wall -Wno-unused-variable
RM = rm -f
MAKE = make
AR = ar rcs
OUTLIB_NAME = out.a
CXX_TEXT = "[CXX]	"
